DROP TABLE IF EXISTS NSB_RESOURCE;
DROP TABLE IF EXISTS NSB_STATUS;

CREATE TABLE NSB_RESOURCE
(
	ID INT AUTO_INCREMENT
		PRIMARY KEY,
	NAME VARCHAR(255) NULL,
	VERSION VARCHAR(255) NULL,
	LABELS VARCHAR(255) NULL,
	CREATE_TIME VARCHAR(255) NULL,
	BODY TEXT NULL
);

CREATE TABLE NSB_STATUS
(
	ID INT AUTO_INCREMENT
		PRIMARY KEY,
	NAME VARCHAR(255) NULL,
	VALUE VARCHAR(255) NULL
);

INSERT NSB_STATUS VALUES('1', 'resources_version', '0');

COMMIT;